### PR TITLE
Fix spelling error: dont -> don't

### PR DESCRIPTION
**Pull request by ottok**

### CODE REVIEW

**Comment by ottok** [comment]
For example Debian QA systems complain about this spelling error inside the binaries, so I decided to make a PR to get them fixed.

**Comment by laurynas-biveinis** [comment]
@georgelorchpercona, @christianrober ?

**Comment by georgelorchpercona** [comment]
Looks good to me, Otto, can you please resubmit with the appropriate license text defined here https://github.com/percona/PerconaFT#contributing

**Comment by ottok** [comment]
I am happy to do that but can you please provide in the README the text paragraph so I can copy-paste it into my commit message, or alternatively link to an example commit with the license text?

**Comment by georgelorchpercona** [comment]
Here is the license template mentioned in the README : https://opensource.org/licenses/BSD-2-Clause/

For an example of a contributor commit message, see this commit https://github.com/percona/PerconaFT/commit/1b5ce3e7a7fe7fdc247550fe8fae012b80856191

Thanks much for the contribution.

**Comment by ottok** [comment]
OK, gotcha. Pushed new commit. I also included Sign-off to alleviate the contribution (as e.g. done in the Linux kernel).

**Comment by georgelorchpercona** [comment]
Perfect, thanks Otto!

**Pull request merged**
