### PR TITLE
pfs leaks memory

### PR DESCRIPTION
**Pull request by prohaska7**
Need to cleanup the pfs memory in the fractal tree library destructor. Detected with valgrind's memory checker (ctest -D ExperimentalMemCheck).

Copyright (c) 2017, Rik Prohaska
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

### CODE REVIEW

**Comment by georgelorchpercona** [comment]
Hey Rik, good to see you around. Thanks for the PR's. I'm tied up at the moment but will review, test, and merge these soon. There is some overlap in these fixes with what I am facing in the port to 8.0, that is a good thing.

**Comment by prohaska7** [comment]
Hello George,
Bohu is interested in running tokudb on mysql 8.

**Comment by BohuTANG** [comment]
Hi George,

That's good to hear you are working on mysql 8, expecting that.

**Comment by georgelorchpercona** [comment]
https://github.com/georgelorchpercona/PerconaFT/tree/prohaska7-pfs-memleak
https://jenkins.percona.com/view/TokuDB/job/PerconaFT-param/109/
https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2046/
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1473/

Manually merged due to rebase and conflict fixup

**Pull request closed without merging**
