### PR TITLE
FT-700 (Replacing ZERO_MUTEX_INITIALIZER with TOKU_MUTEX_INITIALIZER …

### PR DESCRIPTION
**Pull request by laurynas-biveinis**
…is wrong for debug builds)

Revert the bits of FT-699 that cause a debug build crash in
toku_mutex_init because of passing an initialised mutex where an
uninitialised one is expected.

### CODE REVIEW

**Comment by kuszmaul** [comment]
master is still broken (it uses TOKU_MUTEX_INITIALIZER instead of of
ZERO_MUTEX_INITIALIZER).  What's the story with this patch?

On Thu, Sep 10, 2015 at 3:59 AM, Laurynas Biveinis <notifications@github.com

**Comment by georgelorchpercona** [comment]
It's broken and being fixed, tested and verified right now.

On 09/10/2015 10:15 AM, Bradley C. Kuszmaul wrote:
> master is still broken (it uses TOKU_MUTEX_INITIALIZER instead of of
> ZERO_MUTEX_INITIALIZER). What's the story with this patch?
>
> On Thu, Sep 10, 2015 at 3:59 AM, Laurynas Biveinis 
> <notifications@github.com
> > wrote:
>
> > Merged #320 <https://github.com/percona/PerconaFT/pull/320>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/percona/PerconaFT/pull/320#event-405667040>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139315106>.
>

-- 
George O. Lorch III
Software Engineer, Percona
US/Arizona (GMT -7)
skype: george.ormond.lorch.iii

**Comment by kuszmaul** [comment]
OK.  Incidentally I made a pull request (it's on tokutek/ft-index... does
that get mirrored back to percona?  Should I stop using tokutek/ft-index?)

In my pull request, I not only switched it back, but I also wrote a bunch
of explanation about what's going on.

-Bradley

**Comment by georgelorchpercona** [comment]
No, it does not get mirrored back unfortunately. ft-index in the Tokutek 
repo needs to be closed off.

I have a similar fix you can use the use the PTHREAD_MUTEX_INITIALIZER 
macro if C++11, but still not particularly good form.

On 09/10/2015 10:35 AM, Bradley C. Kuszmaul wrote:
> OK. Incidentally I made a pull request (it's on tokutek/ft-index... does
> that get mirrored back to percona? Should I stop using tokutek/ft-index?)
>
> In my pull request, I not only switched it back, but I also wrote a bunch
> of explanation about what's going on.
>
> -Bradley
>
> On Thu, Sep 10, 2015 at 1:22 PM, georgelorchpercona <
> notifications@github.com> wrote:
>
> > It's broken and being fixed, tested and verified right now.
> >
> > On 09/10/2015 10:15 AM, Bradley C. Kuszmaul wrote:
> > > master is still broken (it uses TOKU_MUTEX_INITIALIZER instead of of
> > > ZERO_MUTEX_INITIALIZER). What's the story with this patch?
> > >
> > > On Thu, Sep 10, 2015 at 3:59 AM, Laurynas Biveinis
> > > <notifications@github.com
> > > > wrote:
> > >
> > > > Merged #320 <https://github.com/percona/PerconaFT/pull/320>.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/percona/PerconaFT/pull/320#event-405667040>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139315106>.
> > >
> >
> > --
> > George O. Lorch III
> > Software Engineer, Percona
> > US/Arizona (GMT -7)
> > skype: george.ormond.lorch.iii
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/percona/PerconaFT/pull/320#issuecomment-139316699>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139320305>.
>

-- 
George O. Lorch III
Software Engineer, Percona
US/Arizona (GMT -7)
skype: george.ormond.lorch.iii

**Comment by kuszmaul** [comment]
Is there a branch with the candidate fix?

Bradley C Kuszmaul - via snartphone

**Comment by georgelorchpercona** [comment]
Yeah, I took your fix instead of mine which was similar as yours had 
better commenting. I'll have the master updated shortly once I've 
finished testing, maybe another 15 minutes or so.

On 09/10/2015 11:01 AM, Bradley C. Kuszmaul wrote:
> Is there a branch with the candidate fix?
>
> Bradley C Kuszmaul - via snartphone
> On Sep 10, 2015 1:49 PM, "georgelorchpercona" <notifications@github.com>
> wrote:
>
> > No, it does not get mirrored back unfortunately. ft-index in the Tokutek
> > repo needs to be closed off.
> >
> > I have a similar fix you can use the use the PTHREAD_MUTEX_INITIALIZER
> > macro if C++11, but still not particularly good form.
> >
> > On 09/10/2015 10:35 AM, Bradley C. Kuszmaul wrote:
> > > OK. Incidentally I made a pull request (it's on 
> tokutek/ft-index... does
> > > that get mirrored back to percona? Should I stop using 
> tokutek/ft-index?)
> > >
> > > In my pull request, I not only switched it back, but I also wrote 
> a bunch
> > > of explanation about what's going on.
> > >
> > > -Bradley
> > >
> > > On Thu, Sep 10, 2015 at 1:22 PM, georgelorchpercona <
> > > notifications@github.com> wrote:
> > >
> > > > It's broken and being fixed, tested and verified right now.
> > > >
> > > > On 09/10/2015 10:15 AM, Bradley C. Kuszmaul wrote:
> > > > > master is still broken (it uses TOKU_MUTEX_INITIALIZER instead 
> of of
> > > > > ZERO_MUTEX_INITIALIZER). What's the story with this patch?
> > > > >
> > > > > On Thu, Sep 10, 2015 at 3:59 AM, Laurynas Biveinis
> > > > > <notifications@github.com
> > > > > > wrote:
> > > > >
> > > > > > Merged #320 <https://github.com/percona/PerconaFT/pull/320>.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <https://github.com/percona/PerconaFT/pull/320#event-405667040>.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139315106>.
> > > > >
> > > >
> > > > --
> > > > George O. Lorch III
> > > > Software Engineer, Percona
> > > > US/Arizona (GMT -7)
> > > > skype: george.ormond.lorch.iii
> > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139316699
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139320305>.
> > >
> >
> > --
> > George O. Lorch III
> > Software Engineer, Percona
> > US/Arizona (GMT -7)
> > skype: george.ormond.lorch.iii
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/percona/PerconaFT/pull/320#issuecomment-139323344>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139328696>.
>

-- 
George O. Lorch III
Software Engineer, Percona
US/Arizona (GMT -7)
skype: george.ormond.lorch.iii

**Comment by laurynas-biveinis** [comment]
Sorry about that and thanks for the catch. The commit message of FT-700 is what I tried to do, but apparently messed up.

**Comment by georgelorchpercona** [comment]
OK Bradley, master is up to date, sorry about the mess.

On 09/10/2015 11:01 AM, Bradley C. Kuszmaul wrote:
> Is there a branch with the candidate fix?
>
> Bradley C Kuszmaul - via snartphone
> On Sep 10, 2015 1:49 PM, "georgelorchpercona" <notifications@github.com>
> wrote:
>
> > No, it does not get mirrored back unfortunately. ft-index in the Tokutek
> > repo needs to be closed off.
> >
> > I have a similar fix you can use the use the PTHREAD_MUTEX_INITIALIZER
> > macro if C++11, but still not particularly good form.
> >
> > On 09/10/2015 10:35 AM, Bradley C. Kuszmaul wrote:
> > > OK. Incidentally I made a pull request (it's on 
> tokutek/ft-index... does
> > > that get mirrored back to percona? Should I stop using 
> tokutek/ft-index?)
> > >
> > > In my pull request, I not only switched it back, but I also wrote 
> a bunch
> > > of explanation about what's going on.
> > >
> > > -Bradley
> > >
> > > On Thu, Sep 10, 2015 at 1:22 PM, georgelorchpercona <
> > > notifications@github.com> wrote:
> > >
> > > > It's broken and being fixed, tested and verified right now.
> > > >
> > > > On 09/10/2015 10:15 AM, Bradley C. Kuszmaul wrote:
> > > > > master is still broken (it uses TOKU_MUTEX_INITIALIZER instead 
> of of
> > > > > ZERO_MUTEX_INITIALIZER). What's the story with this patch?
> > > > >
> > > > > On Thu, Sep 10, 2015 at 3:59 AM, Laurynas Biveinis
> > > > > <notifications@github.com
> > > > > > wrote:
> > > > >
> > > > > > Merged #320 <https://github.com/percona/PerconaFT/pull/320>.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <https://github.com/percona/PerconaFT/pull/320#event-405667040>.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139315106>.
> > > > >
> > > >
> > > > --
> > > > George O. Lorch III
> > > > Software Engineer, Percona
> > > > US/Arizona (GMT -7)
> > > > skype: george.ormond.lorch.iii
> > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139316699
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139320305>.
> > >
> >
> > --
> > George O. Lorch III
> > Software Engineer, Percona
> > US/Arizona (GMT -7)
> > skype: george.ormond.lorch.iii
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/percona/PerconaFT/pull/320#issuecomment-139323344>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/percona/PerconaFT/pull/320#issuecomment-139328696>.
>

-- 
George O. Lorch III
Software Engineer, Percona
US/Arizona (GMT -7)
skype: george.ormond.lorch.iii

**Comment by laurynas-biveinis** [comment]
ZERO_COND_INITIALIZER needs the same treatment, logged FT-702, will submit a PR shortly

**Comment by kuszmaul** [comment]
I believe that  d8598d5ef08642a06b202c1c3ec314e37d22cb59 fixes that, but
it's on my side branch.

-Bradley

**Pull request merged**
